[theme]
primaryColor = "#38BDF8"
backgroundColor = "#191414"
secondaryBackgroundColor = "#1E293B"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 25

[browser]
gatherUsageStats = false
